# Generated by Django 4.2.16 on 2024-11-03 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='profile')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('therapy', models.CharField(choices=[('insulin', 'Insulin'), ('Tablets', 'Tablets')], max_length=10)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('diabetes_type', models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Pre Diabetic', 'Pre Diabetic'), ('genetic predisposition', 'genetic predisposition'), ('Normal', 'Normal')], max_length=22)),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
